# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# add the Firebase pod for Google Analytics
platform :ios, '10.0'
# Required by RNFirebase

pod 'Firebase/Core'
pod 'Firebase/Analytics'

target 'worSky' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]


  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  # pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  # pod 'react-native-maps', path: rn_maps_path
  # pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  # pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  # pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'
  pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'
  pod 'RNSensors', :path => '../node_modules/react-native-sensors'

  target 'worsky-tvOSTests' do
    inherit! :search_paths
    # Pods for testing


    pod 'react-native-webview', :path => '../node_modules/react-native-webview'

    pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

    pod 'react-native-compass-heading', :path => '../node_modules/react-native-compass-heading'

    pod 'RNScreens', :path => '../node_modules/react-native-screens'

    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

    pod 'react-native-image-editor', :path => '../node_modules/@react-native-community/image-editor'

    pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

    pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

    pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'


  end

  target 'worskyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end

    targets_to_ignore = %w(React yoga)
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end
  end
end
